### ISSUE TITLE
`No such middleware to insert before: ActionDispatch::DebugExceptions`

### ISSUE THREAD

**Issue by alagos** [discourse/logster#59]
I just added to my Gemfile:
```ruby
gem 'logster'
gem 'redis' # this was already installed because of sidekiq
```
but when I try to start the app, it throws:

```
=> Booting Puma
=> Rails 4.2.7.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/stack.rb:125:in `assert_index': No such middleware to insert before: ActionDispatch::DebugExceptions (RuntimeError)
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/stack.rb:88:in `insert'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/railties-4.2.7.1/lib/rails/configuration.rb:68:in `block in merge_into'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/railties-4.2.7.1/lib/rails/configuration.rb:67:in `each'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/railties-4.2.7.1/lib/rails/configuration.rb:67:in `merge_into'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/railties-4.2.7.1/lib/rails/engine.rb:501:in `app'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/railties-4.2.7.1/lib/rails/application/finisher.rb:34:in `block in <module:Finisher>'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /files/alter/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
        from /files/alter/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
        from /files/alter/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
        from /files/alter/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
        from /files/alter/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/tsort.rb:345:in `each'
        from /files/alter/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/tsort.rb:345:in `call'
        from /files/alter/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
        from /files/alter/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
        from /files/alter/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
        from /files/alter/workspace/productswatcher/config/environment.rb:5:in `<top (required)>'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
        from /files/alter/workspace/productswatcher/config.ru:3:in `block in <main>'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/rack-1.6.8/lib/rack/builder.rb:55:in `instance_eval'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/rack-1.6.8/lib/rack/builder.rb:55:in `initialize'
        from /files/alter/workspace/productswatcher/config.ru:in `new'
        from /files/alter/workspace/productswatcher/config.ru:in `<main>'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/rack-1.6.8/lib/rack/builder.rb:49:in `eval'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/rack-1.6.8/lib/rack/builder.rb:49:in `new_from_string'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/rack-1.6.8/lib/rack/builder.rb:40:in `parse_file'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/rack-1.6.8/lib/rack/server.rb:300:in `build_app_and_options_from_config'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/rack-1.6.8/lib/rack/server.rb:209:in `app'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/railties-4.2.7.1/lib/rails/commands/server.rb:61:in `app'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/rack-1.6.8/lib/rack/server.rb:337:in `wrapped_app'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/railties-4.2.7.1/lib/rails/commands/server.rb:139:in `log_to_stdout'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/railties-4.2.7.1/lib/rails/commands/server.rb:78:in `start'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:80:in `block in server'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `server'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
        from /files/alter/workspace/productswatcher/bin/rails:8:in `require'
        from /files/alter/workspace/productswatcher/bin/rails:8:in `<top (required)>'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/spring-1.7.1/lib/spring/client/rails.rb:28:in `load'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/spring-1.7.1/lib/spring/client/rails.rb:28:in `call'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/spring-1.7.1/lib/spring/client/command.rb:7:in `call'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/spring-1.7.1/lib/spring/client.rb:30:in `run'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/spring-1.7.1/bin/spring:49:in `<top (required)>'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/spring-1.7.1/lib/spring/binstub.rb:11:in `load'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/spring-1.7.1/lib/spring/binstub.rb:11:in `<top (required)>'
        from /files/alter/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /files/alter/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /files/alter/workspace/productswatcher/bin/spring:13:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'

```

and it happens adding or not the `mount` to my `routes.rb` file. 
What I'm missing here?

**Comment by alagos** [comment]
Oh, I just realized about the [note](https://github.com/discourse/logster#note). Closing
